export const TRANSACTION_TYPES = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
  TRANSFER: 'TRANSFER'
};

export const TRANSACTION_STATUSES = {
  COMPLETED: 'COMPLETED',
  PENDING: 'PENDING',
  CANCELLED: 'CANCELLED'
};

export const RECURRING_FREQUENCIES = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY'
};

export const STATEMENT_STATUSES = {
  UNPAID: 'UNPAID',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID'
};

export const ATTACHMENT_TYPES = {
  IMAGE: 'IMAGE',
  PDF: 'PDF',
  OTHER: 'OTHER'
};

export const AUDIT_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  TRANSFER: 'TRANSFER',
  CC_PAYMENT: 'CC_PAYMENT'
};

export const TRANSACTION_TYPE_LIST = Object.values(TRANSACTION_TYPES);
export const TRANSACTION_STATUS_LIST = Object.values(TRANSACTION_STATUSES);
export const RECURRING_FREQUENCY_LIST = Object.values(RECURRING_FREQUENCIES);
export const STATEMENT_STATUS_LIST = Object.values(STATEMENT_STATUSES);
export const ATTACHMENT_TYPE_LIST = Object.values(ATTACHMENT_TYPES);
export const AUDIT_ACTION_LIST = Object.values(AUDIT_ACTIONS);
